name: html

on:
  push:
    branches:
      - 1-test
  pull_request:
    branches:
      - main
 
jobs:
  build:
    runs-on: self-hosted
 
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
 
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
 
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
 
    - name: Run unit tests and generate coverage report
      run: |
        pytest --cov=my_package --cov-report html
      continue-on-error: true
 
    - name: Upload coverage report as artifact
      uses: actions/upload-artifact@v2
      with:
        name: coverage-report
        path: htmlcov/
 
    - name: Generate Preview Link
      id: create-link
      uses: actions/github-script@v4
      with:
        script: |
          const artifactId = context.runId;
          const repo = context.repo.repo;
          const owner = context.repo.owner;
          const htmlPath = 'htmlcov/index.html';
          const previewUrl = `https://github.com/${owner}/${repo}/suites/${artifactId}/artifacts/${htmlPath}`;
          core.setOutput("preview_url", previewUrl);
 
    - name: Print Preview Link
      run: echo "Preview URL:${{ steps.create-link.outputs.preview_url }}"
      if: always()
