name: CI Workflow

on:
  push:
    branches:
      - test
  pull_request:
    branches:
      - main

jobs:
  test-and-report:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies and tools
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install junit2html

      - name: Run tests and convert report to HTML
        run: |
          pytest --junitxml=reports/junit.xml
          mkdir -p reports
          ~/.local/bin/junit2html reports/junit.xml reports/junit.html

      - name: Upload HTML report
        uses: actions/upload-artifact@v2
        with:
          name: html-report
          path: reports/junit.html

      - name: Commit HTML report to test branch
        run: |
          git fetch origin
          git checkout -B test origin/test
          cp reports/junit.html .
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add junit.html
          git commit -m "Update HTML report"
          git pull --rebase origin test
          git push origin test

      - name: Get repository and branch info
        id: repo-info
        run: |
          echo "::set-output name=repo_url::$(echo https://github.com/${{ github.repository }}/blob/test/junit.html)"

      - name: Post HTML preview link as comment
        if: github.event_name == 'pull_request'
        uses: peter-evans/create-or-update-comment@v2
        with:
          token: ${{ secrets.TOKEN_GITHUB }}
          repository: ${{ github.repository }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            HTML preview is available [here](${{ steps.repo-info.outputs.repo_url }})
