name: CI Workflow

on:
  workflow_dispatch:

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Specify the Python version you need

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        id: run-tests
        run: |
          pytest --junitxml=reports/junit.xml --tb=short
          pytest --junitxml=reports/junit.xml --tb=short --maxfail=1 || echo "Test failed"

      - name: Upload JUnit test report
        uses: actions/upload-artifact@v2
        with:
          name: junit-report
          path: reports/junit.xml

      - name: Convert JUnit XML to HTML
        run: |
          pip install junit2html
          junit2html reports/junit.xml reports/junit.html

      - name: Upload HTML report
        uses: actions/upload-artifact@v2
        with:
          name: html-report
          path: reports/junit.html

      - name: Generate Test Summary
        id: test-summary
        run: |
          echo "## Test Results Summary" > results-summary.md
          echo "| Test File | Result |" >> results-summary.md
          echo "| --------- | ------ |" >> results-summary.md
          pytest --tb=short --maxfail=1 --junitxml=results-summary.md
          cat results-summary.md

      - name: Post Test Summary as a Comment
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const summary = fs.readFileSync('results-summary.md', 'utf8');
            github.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: summary
            })

  html-report:
    runs-on: ubuntu-latest
    needs: pytest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download JUnit report
        uses: actions/download-artifact@v2
        with:
          name: junit-report
          path: reports 

      - name: Install junit2html
        run: |
          sudo apt-get update
          sudo apt-get install python3-pip  # Install pip for Python 3
          pip3 install junit2html

      - name: Convert JUnit XML to HTML
        run: |
          junit2html reports/junit.xml reports/junit.html

      - name: Upload HTML report
        uses: actions/upload-artifact@v2
        with:
          name: html-report
          path: reports/junit.html

      - name: HTML Preview
        uses: actions/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages
          folder: reports
          clean: true
