name: Generate and Preview HTML Report

on:
  pull_request:
    types: [opened, synchronize, reopened]
 
jobs:
  build:
    runs-on: self-hosted
 
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
 
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
 
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
 
    - name: Run unit tests and generate coverage report
      run: |
        pytest --cov=my_package --cov-report html
      continue-on-error: true
 
    - name: Upload coverage report as artifact
      uses: actions/upload-artifact@v2
      with:
        name: coverage-report
        path: htmlcov/
 
    - name: Preview coverage report
      uses: martinsson/preview-artifact@v1
      with:
        name: coverage-report
        path: htmlcov/index.html
