name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pytest:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}  # Ensure checkout of the current branch

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest --junitxml=reports/junit.xml

      - name: Upload JUnit test report
        uses: actions/upload-artifact@v2
        with:
          name: junit-report
          path: reports/junit.xml

  html-report:
    runs-on: self-hosted
    needs: pytest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}  # Ensure checkout of the current branch

      - name: Download JUnit report
        uses: actions/download-artifact@v2
        with:
          name: junit-report
          path: reports 

      - name: Install junit2html
        run: |
          sudo apt-get update
          sudo apt-get install python3-pip  # Install pip for Python 3
          pip3 install junit2html

      - name: Convert JUnit XML to HTML
        run: |
          ~/.local/bin/junit2html reports/junit.xml index.html

      - name: Commit and push HTML report
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add index.html
          git commit -m "Add HTML report"
          git push origin HEAD:main  # Push to the main branch

      - name: HTML Preview
        id: html_preview
        uses: pavi2410/html-preview-action@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          artifact_name: html-report
          file: index.html

      - name: Get HTML Preview URL
        run: echo "HTML Preview URL:${{ steps.html_preview.outputs.url }}"
