name: Run Python Function and Generate Report

on:
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run script and generate report
      run: |
        python my_script.py

    - name: Upload report
      uses: actions/upload-artifact@v2
      with:
        name: report
        path: report.html

    - name: Post report link as PR comment
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        REPORT_URL=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
          "https://api.github.com/repos/${{ github.repository }}/actions/artifacts" \
          | jq -r '.artifacts[] | select(.name=="report") | .archive_download_url')
        
        COMMENT="### :page_facing_up: Report\n\nYou can download the report [here](${REPORT_URL})"
        
        curl -s -H "Authorization: token $GITHUB_TOKEN" \
          -H "Content-Type: application/json" \
          -X POST \
          -d "{\"body\":\"${COMMENT}\"}" \
          "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments"
