name: CI Workflow

on:
  push:
    branches:
      - test
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Replace with your desired Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Run tests and capture results
        run: |
          pytest --junitxml=results.xml

      - name: Display test results in job summary
        run: |
          echo '### Unit Test Results' >> $GITHUB_STEP_SUMMARY
          echo '<details>' >> $GITHUB_STEP_SUMMARY
          echo '<summary>Click to expand</summary>' >> $GITHUB_STEP_SUMMARY
          echo '<pre>' >> $GITHUB_STEP_SUMMARY
          cat results.xml >> $GITHUB_STEP_SUMMARY
          echo '</pre>' >> $GITHUB_STEP_SUMMARY
          echo '</details>'
