name: Run Tests and Generate Job Summary

on:
  push:
    branches:
      - test
  pull_request:
    branches:
      - main


 
jobs:
  test-and-summary:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
 
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
 
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest-html
 
      - name: Run tests and generate HTML report
        id: run_tests
        run: |
          pytest --html=report.html --self-contained-html
 
      - name: Upload HTML report as artifact
        uses: actions/upload-artifact@v2
        with:
          name: pytest-report
          path: report.html
 
      - name: Add report link to job summary
        if: always()
        run: |
          echo "### Test Report" >> $GITHUB_STEP_SUMMARY
          echo "The test results are available [here](../artifacts/pytest-report/report.html)" >> $GITHUB_STEP_SUMMARY

          echo "<a href='${{ steps.upload_artifacts.outputs.download_url }}'>View the detailed test report</a>" >> $GITHUB_STEP_SUMMARY

    
