name: Complex Workflow Summary

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Run tests and generate results
      - name: Run tests
        run: |
          echo "Running tests..."
          # Simulate test results
          echo "### Test Results" >> $GITHUB_STEP_SUMMARY
          echo "Test1: PASS" >> $GITHUB_STEP_SUMMARY
          echo "Test2: FAIL" >> $GITHUB_STEP_SUMMARY
          echo "Test3: PASS" >> $GITHUB_STEP_SUMMARY

      # Gather metrics
      - name: Gather metrics
        run: |
          echo "Gathering metrics..."
          # Simulate metrics
          echo "### Metrics" >> $GITHUB_STEP_SUMMARY
          echo "Metric1: 95%" >> $GITHUB_STEP_SUMMARY
          echo "Metric2: 80%" >> $GITHUB_STEP_SUMMARY

      # Upload detailed results and metrics as artifacts
      - name: Upload test results
        run: |
          echo "Test1: PASS" > results.txt
          echo "Test2: FAIL" >> results.txt
          echo "Test3: PASS" >> results.txt
          echo "Metric1: 95%" > metrics.txt
          echo "Metric2: 80%" >> metrics.txt
        uses: actions/upload-artifact@v2
        with:
          name: detailed-results
          path: |
            results.txt
            metrics.txt
