name: CI Workflow

on:
  push:
    branches:
      - test
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Replace with your desired Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Run tests and capture results
        run: |
          pytest --junitxml=test/results/TEST-results.xml

      - name: Test Summary
        uses: test-summary/action@v2
        with:
          paths: "test/results/TEST-results.xml"
         
        if: always()

