name: CI Workflow

on:
  push:
    branches:
      - test
  pull_request:
    branches:
      - main

jobs:

  test-and-summary:

    runs-on: self-hosted
 
    steps:

    - name: Checkout code

      uses: actions/checkout@v2
 
    - name: Set up Python

      uses: actions/setup-python@v2

      with:

        python-version: '3.8'
 
    - name: Install dependencies

      run: pip install -r requirements.txt
 
    - name: Run tests and generate HTML report
      id: run_tests
      run: |
        pytest --html=report.html --self-contained-html
 
    - name: Display HTML report in job summary
      if: always()
      run: |
        echo "### Test Report" >> $GITHUB_STEP_SUMMARY
        echo '<h2>Test Results</h2>' >> $GITHUB_STEP_SUMMARY
        echo '<pre>' >> $GITHUB_STEP_SUMMARY
        cat report.html >> $GITHUB_STEP_SUMMARY
        echo '</pre>' >> $GITHUB_STEP_SUMMARY
