name: Run Tests and Generate Job Summary


on:
  push:
    branches:
      - test
  pull_request:
    branches:
      - main



jobs:
  test-and-summary:
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-html
      
    - name: Run tests and generate HTML report
      id: run_tests
      run: |
        pytest --html=report.html
        
    - name: Upload HTML Report
      uses: actions/upload-artifact@v2
      with:
        name: html-report
        path: report.html

    - name: Display HTML Report in Job Summary
      uses: actions/github-script@v4
      with:
        script: |
          const fs = require('fs');
          const htmlReport = fs.readFileSync('report.html', 'utf8');
          console.log(`::set-output name=summary::${htmlReport}`);
