name: Run Tests and Generate Job Summary

on:
  push:
    branches:
      - test
  pull_request:
    branches:
      - main

jobs:
  test-and-summary:
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
           
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        
    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Install jq
      run: sudo apt-get install jq
      
    - name: Run tests and generate reports
      id: run_tests
      run: |
        pytest --json-report --json-report-file=report.json --html=report.html
        
    - name: Upload HTML Report
      uses: actions/upload-artifact@v2
      with:
        name: html-report
        path: report.html  
      
    - name: Generate job summary
      if: always()
      run: |
        echo "### Job Summary" >> $GITHUB_STEP_SUMMARY

        echo "<h2>Test Results</h2>" >> $GITHUB_STEP_SUMMARY

        RESULTS=$(cat report.json | jq '.summary')
        TESTS_TOTAL=$(echo $RESULTS | jq '.total')
        TESTS_SKIPPED=$(echo $RESULTS | jq '.skipped')
        TESTS_FAILED=$(echo $RESULTS | jq '.failed')
        TESTS_PASSED=$(echo $RESULTS | jq '.passed')
        TESTS_ERRORS=$(echo $RESULTS | jq '.errors')
        TESTS_DURATION=$(echo $RESULTS | jq '.duration')

        echo "<table>" >> $GITHUB_STEP_SUMMARY
        echo "<tr><th>Tests</th><th>Skipped</th><th>Failed</th><th>Passed</th><th>Error</th><th>Time</th></tr>" >> $GITHUB_STEP_SUMMARY
        echo "<tr><td>${TESTS_TOTAL}</td><td>${TESTS_SKIPPED}</td><td>${TESTS_FAILED}</td><td>${TESTS_PASSED}</td><td>${TESTS_ERRORS}</td><td>${TESTS_DURATION} sec</td></tr>" >> $GITHUB_STEP_SUMMARY
        echo "</table>" >> $GITHUB_STEP_SUMMARY

        echo "<a href='${{ steps.upload_artifacts.outputs.download_url }}'>View the detailed test report</a>" >> $GITHUB_STEP_SUMMARY

    
