name: Complex Workflow Summary

on: [push]

jobs:
  build:
    runs-on: self-hosted

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Run tests and generate results
      - name: Run tests
        run: |
          echo "Running tests..."
          # Simulate test results
          echo "Test1: PASS" > results.txt
          echo "Test2: FAIL" >> results.txt
          echo "Test3: PASS" >> results.txt

      # Gather metrics
      - name: Gather metrics
        run: |
          echo "Gathering metrics..."
          # Simulate metrics
          echo "Metric1: 95%" > metrics.txt
          echo "Metric2: 80%" >> metrics.txt

      # Combine results and metrics
      - name: Combine results and metrics
        run: |
          cat results.txt metrics.txt > summary.txt

      # Display custom summary information
      - name: Display summary
        run: |
          cat summary.txt
          while IFS= read -r line
          do
            echo "::notice::$line"
          done < summary.txt

      # Upload results and metrics as artifacts
      - name: Upload summary
        uses: actions/upload-artifact@v2
        with:
          name: summary
          path: summary.txt
